name: Docker Compose CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Check directory
      run: echo "$PWD"

    - name: Set up Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose tree
      
    - name: check binds
      run: ls -l src/

    - name: Build Docker images using docker-compose
      run: docker-compose build
